import fs from 'fs';
import { GlobSync } from 'glob';
import _ from 'lodash';
import util from 'util';

import { generate_compound } from './generate_compound';
import { generate_compound_interface } from './generate_compound_interface';
import { generate_entity } from './generate_entity';
// import { generateInterface } from './generate_entity_interface';
// import { generate_sql } from './generate_sql';
import { JsCoder } from '../lib/JsCoder';
import { Config } from './spec';
import { ITable } from 'model';
// import { compounds, tables } from './tables';
const tables: ITable[] = [];
const compounds: {name: string, tables: ITable[]}[] = [];

const config: Config = {
	mrshopDir: '..'
};

let unnecessaryFiles: string[] = [];

// create sql files: scheme/tables/*.sql
// {
// 	const filedir = `${config.mrshopDir}/scheme/tables`;
// 	if (fs.existsSync(filedir)) {
// 		unnecessaryFiles.push(...new GlobSync(`${filedir}/*.sql`).found);
// 	} else {
// 		fs.mkdirSync(filedir);
// 		console.log(`${filedir} created.`);
// 	}

// 	_.each(tables, (table) => {
// 		const code = generate_sql(table, config);
// 		const filepath = `${filedir}/${table.name}.sql`;
// 		fs.writeFileSync(filepath, code);
// 		console.log(`${filepath} generated.`);
// 		_.remove(unnecessaryFiles, f => f === filepath);
// 	});
// }

// create interface files: scheme/src/entity/types/*.ts
// {
// 	const js = new JsCoder();
// 	js.add(`
// 	/* DO NOT EDIT THIS FILE:
// 	* This file is generated by mrshop-gencode project.
// 	*/`);

// 	const filedir = `${config.mrshopDir}/scheme/src/entity/types`;
// 	if (fs.existsSync(filedir)) {
// 		unnecessaryFiles.push(...new GlobSync(`${filedir}/*.ts`).found);
// 	} else {
// 		console.log(`${filedir} created.`);
// 		fs.mkdirSync(filedir, {recursive: true});
// 	}

// 	_.each(tables, (table) => {
// 		const code = generateInterface(table, config);
// 		const filepath = `${filedir}/${table.entityName}.ts`;
// 		fs.writeFileSync(filepath, code);
// 		console.log(`${filepath} generated.`);
// 		_.remove(unnecessaryFiles, f => f === filepath);

// 		js.add(`export * from './${table.entityName}';`)
// 	});

// 	_.each(compounds, (compound) => {
// 		const code = generate_compound_interface(compound.name, compound.tables, config);
// 		const filepath = `${filedir}/${compound.name}.ts`;
// 		fs.writeFileSync(filepath, code);
// 		console.log(`${filepath} generated.`);
// 		_.remove(unnecessaryFiles, f => f === filepath);

// 		js.add(`export * from './${compound.name}';`)
// 	});

// 	const filepath = `${filedir}/index.ts`;
// 	fs.writeFileSync(filepath, js.toString());
// 	console.log(`${filepath} generated.`);
// 	_.remove(unnecessaryFiles, f => f === filepath);
// }

// create entity files: server/src/dao/entity/*.Entity.ts
{
	const js = new JsCoder();
	js.add(`
	/* DO NOT EDIT THIS FILE:
	* This file is generated by mrshop-gencode project.
	*/`);

	const filedir = `${config.mrshopDir}/server/src/dao/entity`;
	if (fs.existsSync(filedir)) {
		unnecessaryFiles.push(...new GlobSync(`${filedir}/*.Entity.ts`).found);
	} else {
		console.log(`${filedir} created.`);
		fs.mkdirSync(filedir);
	}

	_.each(tables, (table) => {
		const code = generate_entity(table, config);
		const filepath = `${filedir}/${table.entityName}.Entity.ts`;
		fs.writeFileSync(filepath, code);
		console.log(`${filepath} generated.`);
		_.remove(unnecessaryFiles, f => f === filepath);

		js.add(`export * from './${table.entityName}.Entity';`)
	});

	_.each(compounds, (compound) => {
		const code = generate_compound(compound.name, compound.tables, config);
		const filepath = `${filedir}/${compound.name}.Entity.ts`;
		fs.writeFileSync(filepath, code);
		console.log(`${filepath} generated.`);
		_.remove(unnecessaryFiles, f => f === filepath);

		js.add(`export * from './${compound.name}.Entity';`)
	});

	const filepath = `${filedir}/index.ts`;
	fs.writeFileSync(filepath, js.toString());
	console.log(`${filepath} generated.`);
	_.remove(unnecessaryFiles, f => f === filepath);
}

// create table-specs file: server/src/dao/entity/table-specs.ts
{
	const code = `
/* DO NOT EDIT THIS FILE:
 * This file is generated by mrshop-gencode project.
 */

export interface IField {
	name: string;
	type: string;
	notnull: boolean;
	auto_increment: boolean;
	pk: boolean;
	jstype: string;
	desc?: string;
}

export interface ITable {
	name: string;
	entityName: string;
	fields: IField[];
	constraints?: string[];
	desc?: string;
	fetchLock?: boolean;
}

export const TableSpecs: ITable[] = ${util.inspect(tables, {depth: null})};
	`.trim();

	const filepath = `${config.mrshopDir}/server/src/dao/entity/table-specs.ts`;
	fs.writeFileSync(filepath, code);
	console.log(`${filepath} generated.`);
}

console.log('----------------------------');

if (unnecessaryFiles.length) {
	console.log(`There are ${unnecessaryFiles.length} of unnecessary files. If you want to delete them, just do:`);
	console.log(`$ rm -rf ${unnecessaryFiles.join(' ')}`);

} else {
	console.log('Done.');
}
